# Provide sudo permissions
sudo:required

# Specify the required services
services:
  - docker

# Specify the things that we need to do before our tests run
before_install:
  - docker build -t docker/frontend -f Dockerfile.dev .
